### PR TITLE
Linux file

### PR DESCRIPTION
**Pull request by ninjagolloyd**
Formats linux

### CODE REVIEW

**Comment by i5o** [comment]
You need sudo, and also, I think you need a argument for this. XD

So close, sorry

**Comment by ninjagolloyd** [comment]
-rf is an argument. R is recursive and f is force.

**Comment by i5o** [comment]
What is lovvv

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-06-01 17:45 GMT-03:00 ninjagolloyd <notifications@github.com>:

**Comment by ninjagolloyd** [comment]
Uh what?

**Comment by i5o** [comment]
XD I will merge this.

Thanks

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-06-01 19:05 GMT-03:00 ninjagolloyd <notifications@github.com>:

**Comment by ninjagolloyd** [comment]
> what is lovvvvvvv


# What

**Comment by i5o** [comment]
idk

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-06-01 19:15 GMT-03:00 ninjagolloyd <notifications@github.com>:

**Comment by ninjagolloyd** [comment]
Um

**Comment by i5o** [comment]
Ok

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-06-01 19:26 GMT-03:00 ninjagolloyd <notifications@github.com>:

**Comment by ninjagolloyd** [comment]
Can't commit after closing so I made a new request and added sudo xD

**Comment by ninjagolloyd** [comment]
> __*i5o wrote:*__
> OK





Lol

**Pull request closed without merging**
